### ISSUE TITLE
サイドメニューの作成

### ISSUE THREAD

**Issue by masaokaka** [masaokaka/my-fridge-frontend#5]

**Comment by daikiku10** [comment]
# 概要
以下のデザインを参考にサイドメニューを作成する。
- PC：https://xd.adobe.com/view/bc238b6c-8846-414f-bb29-3118487e3467-e970/screen/12828129-88ae-4788-b674-3f7da55fbad0/specs/
- モバイル：https://xd.adobe.com/view/bc238b6c-8846-414f-bb29-3118487e3467-e970/screen/d5f4685e-dd70-4c2a-8fce-d52128b66f79/specs/
